import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
Data = pd.read_csv("meteo_tunis.csv")
Data = Data[Data['hour'] != "N/A"]
Data['temperature'] = Data['temperature'].str.replace('°', '', regex=False)
Data['temperature'] = pd.to_numeric(Data['temperature'], errors='coerce')
Data.drop_duplicates(inplace=True)
Data.dropna(inplace=True)
print("\n✅ Aperçu des premières lignes :")
print(Data.head())
print("\n📊 Résumé statistique :")
print(Data.describe())
print("\nℹ️ Structure des données :")
print(Data.info())
plt.figure(figsize=(10,6))
sns.lineplot(data=Data, x='hour', y='temperature', marker='o', color='orangered')
plt.title("🌡️ Température par Heure à Tunis", fontsize=14)
plt.xlabel("Heure")
plt.ylabel("Température (°C)")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8,5))
sns.countplot(data=Data, y='description', palette='viridis')
plt.title("☁️ Fréquence des descriptions météo")
plt.xlabel("Nombre d’occurrences")
plt.ylabel("Type de météo")
plt.tight_layout()
plt.show()
Data['wind_kmh'] = Data['wind_value'].str.extract(r'(\d+)').astype(float)
plt.figure(figsize=(10,6))
sns.barplot(data=Data, x='hour', y='wind_kmh', palette='Blues')
plt.title("💨 Vitesse du Vent par Heure")
plt.xlabel("Heure")
plt.ylabel("Vitesse (km/h)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
Data.to_csv("Cleaned_Data.csv",index=False)